import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import {
  Brain,
  Target,
  Trophy,
  BarChart3,
  ArrowRight,
  CheckCircle2,
  Users,
  BookOpen,
  Zap,
} from 'lucide-react'
import { Logo } from '@/components/marketing/Logo'
import { Footer } from '@/components/marketing/Footer'

const features = [
  {
    icon: Brain,
    title: 'AI-Personalized Curriculum',
    description: 'A custom learning path generated by AI based on your experience, goals, and available time.',
  },
  {
    icon: Target,
    title: 'Structured Assignments',
    description: 'Weekly assignments with deadlines, grades, and feedback to keep you accountable.',
  },
  {
    icon: BarChart3,
    title: 'Progress Tracking',
    description: 'Visual charts, daily streaks, and analytics to monitor your growth every week.',
  },
  {
    icon: Trophy,
    title: 'Project Portfolio',
    description: 'Showcase completed projects, get featured, and build a portfolio that gets you hired.',
  },
  {
    icon: BookOpen,
    title: 'Full MERN Curriculum',
    description: 'MongoDB, Express, React, Node.js, TypeScript, Next.js — everything in one place.',
  },
  {
    icon: Users,
    title: 'Community',
    description: 'Connect with fellow learners, share progress, and get unstuck faster together.',
  },
]

const stats = [
  { value: '50+', label: 'Lessons' },
  { value: '20+', label: 'Projects' },
  { value: '120h', label: 'of Content' },
  { value: '10K+', label: 'Developers' },
]

const techStack = [
  { name: 'MongoDB', label: 'Database' },
  { name: 'Express.js', label: 'Backend' },
  { name: 'React', label: 'Frontend' },
  { name: 'Node.js', label: 'Runtime' },
  { name: 'TypeScript', label: 'Language' },
  { name: 'Next.js', label: 'Framework' },
]

const curriculumModules = [
  { title: 'JavaScript & TypeScript', topics: ['ES6+', 'TypeScript', 'Async Patterns'] },
  { title: 'Frontend', topics: ['React', 'Next.js', 'State', 'UI Libs'] },
  { title: 'Backend', topics: ['Node.js', 'Express', 'API Design', 'Auth'] },
  { title: 'Database & DevOps', topics: ['MongoDB', 'Prisma', 'Docker'] },
]

export default function HomePage() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      {/* Nav */}
      <nav className="sticky top-0 z-50 border-b border-border bg-background/80 backdrop-blur-sm">
        <div className="max-w-5xl mx-auto px-6 h-16 flex items-center justify-between">
          <Logo size="sm" />
          <div className="hidden md:flex items-center gap-6">
            <Link href="#features" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              Features
            </Link>
            <Link href="#curriculum" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              Curriculum
            </Link>
            <Link href="#stats" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
              Stats
            </Link>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/login" className="text-sm text-muted-foreground hover:text-foreground transition-colors hidden sm:block">
              Sign in
            </Link>
            <Link href="/register">
              <Button size="sm" className="gap-2">
                Get Started
                <ArrowRight className="h-4 w-4" />
              </Button>
            </Link>
          </div>
        </div>
      </nav>

      <main className="flex-1">
        {/* Hero */}
        <section className="pt-24 pb-20 px-6">
          <div className="max-w-3xl mx-auto text-center">
            <Badge variant="outline" className="mb-6 text-xs font-medium px-3 py-1">
              New: AI-Powered Personalized Learning
            </Badge>

            <h1 className="text-4xl sm:text-5xl font-bold text-foreground leading-tight tracking-tight mb-6">
              Master the MERN Stack with{' '}
              <span className="text-[var(--primary)]">AI-Personalized</span>{' '}
              Learning
            </h1>

            <p className="text-lg text-muted-foreground mb-10 leading-relaxed max-w-xl mx-auto">
              Get a custom curriculum tailored to your experience, goals, and schedule.
              Track progress with assignments, grades, streaks, and a project portfolio.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-3 mb-8">
              <Link href="/register">
                <Button size="lg" className="w-full sm:w-auto gap-2 px-6">
                  Start Learning Free
                  <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
              <Link href="#features">
                <Button size="lg" variant="outline" className="w-full sm:w-auto px-6">
                  See How It Works
                </Button>
              </Link>
            </div>

            <div className="flex flex-wrap items-center justify-center gap-6 text-xs text-muted-foreground">
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="h-3.5 w-3.5 text-[var(--primary)]" />
                No credit card required
              </span>
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="h-3.5 w-3.5 text-[var(--primary)]" />
                Cancel anytime
              </span>
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="h-3.5 w-3.5 text-[var(--primary)]" />
                Lifetime access
              </span>
            </div>
          </div>
        </section>

        {/* Stats */}
        <section id="stats" className="border-y border-border bg-secondary/20 py-16 px-6">
          <div className="max-w-4xl mx-auto">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              {stats.map((stat) => (
                <div key={stat.label} className="text-center">
                  <div className="text-3xl font-bold text-[var(--primary)] mb-1">{stat.value}</div>
                  <div className="text-sm text-muted-foreground">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Features */}
        <section id="features" className="py-20 px-6">
          <div className="max-w-5xl mx-auto">
            <div className="text-center mb-14">
              <h2 className="text-3xl font-bold text-foreground mb-3">
                Everything you need to master the MERN stack
              </h2>
              <p className="text-muted-foreground max-w-lg mx-auto">
                Our platform combines AI personalization with structured learning to help you progress faster.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
              {features.map((feature) => (
                <Card key={feature.title} className="border-border/60 hover:border-[var(--primary)]/40 transition-colors">
                  <CardHeader className="pb-3">
                    <div className="flex items-center gap-3">
                      <div className="p-2 rounded-lg bg-[var(--primary)]/10 text-[var(--primary)]">
                        <feature.icon className="h-5 w-5" />
                      </div>
                      <CardTitle className="text-base">{feature.title}</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground leading-relaxed">
                      {feature.description}
                    </p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>

        {/* Tech Stack */}
        <section className="py-20 px-6 border-y border-border bg-secondary/20">
          <div className="max-w-3xl mx-auto text-center">
            <h2 className="text-3xl font-bold text-foreground mb-3">
              Full MERN Stack & Modern Tooling
            </h2>
            <p className="text-muted-foreground mb-10">
              Learn the complete ecosystem used by top companies worldwide.
            </p>

            <div className="grid grid-cols-3 md:grid-cols-6 gap-3">
              {techStack.map((tech) => (
                <div
                  key={tech.name}
                  className="flex flex-col items-center gap-1.5 p-4 rounded-xl border border-border bg-background hover:border-[var(--primary)]/40 hover:shadow-sm transition-all"
                >
                  <span className="text-sm font-semibold text-foreground">{tech.name}</span>
                  <span className="text-xs text-muted-foreground">{tech.label}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Curriculum */}
        <section id="curriculum" className="py-20 px-6">
          <div className="max-w-5xl mx-auto">
            <div className="text-center mb-14">
              <h2 className="text-3xl font-bold text-foreground mb-3">
                What you&apos;ll learn
              </h2>
              <p className="text-muted-foreground max-w-lg mx-auto">
                A comprehensive curriculum designed to take you from beginner to job-ready.
              </p>
            </div>

            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
              {curriculumModules.map((module) => (
                <Card key={module.title} className="border-border/60">
                  <CardHeader className="pb-3">
                    <CardTitle className="text-sm font-semibold">{module.title}</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-1.5">
                      {module.topics.map((topic) => (
                        <li key={topic} className="flex items-center gap-2 text-sm text-muted-foreground">
                          <CheckCircle2 className="h-3.5 w-3.5 text-[var(--primary)] shrink-0" />
                          {topic}
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              ))}
            </div>

            <div className="text-center mt-10">
              <Link href="/register">
                <Button size="lg" className="gap-2 px-8">
                  Start Your Personalized Journey
                  <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="py-20 px-6 border-t border-border bg-secondary/20">
          <div className="max-w-2xl mx-auto text-center">
            <div className="rounded-2xl border border-border bg-background p-10 shadow-sm">
              <div className="inline-flex items-center justify-center p-3 rounded-xl bg-[var(--primary)]/10 text-[var(--primary)] mb-6">
                <Zap className="h-6 w-6" />
              </div>
              <h2 className="text-2xl sm:text-3xl font-bold text-foreground mb-4">
                Ready to level up your MERN skills?
              </h2>
              <p className="text-muted-foreground mb-8 leading-relaxed">
                Join thousands of developers building real projects, tracking progress, and getting hired.
              </p>
              <Link href="/register">
                <Button size="lg" className="gap-2 px-8">
                  Create Free Account
                  <ArrowRight className="h-4 w-4" />
                </Button>
              </Link>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
